# -*- coding: utf-8 -*-
"""
/***************************************************************************
 LongLinea
                                 A QGIS plugin
 Plugin que indica al usuario la longitud de una línea seleccionada en la capa activa
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-03-29
        copyright            : (C) 2023 by Alejandra Herrán/Udistrital
        email                : yaherranu@correo.udistrital.edu.co
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load LongLinea class from file LongLinea.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .long_linea import LongLinea
    return LongLinea(iface)
